{
 "title": "Middleware",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Passenger Evasion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "unvalidated_passengers_count", "legendFormat": "{{vehicle_id}}" }
   ]
  },
  {
   "title": "High Passenger Evasion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "unvalidated_passengers_count > 20",
     "legendFormat": "{{vehicle_id}}"
    }
   ]
  },
  {
   "title": "Occupancy Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "occupancy_percentage", "legendFormat": "{{vehicle_id}}" }
   ]
  },
  {
   "title": "High Occupancy Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "occupancy_percentage > 75", "legendFormat": "{{vehicle_id}}" }
   ]
  },
  {
   "title": "Vehicle Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "vehicle_temperature ", "legendFormat": "{{vehicle_id}}" }
   ]
  },
  {
   "title": "High Vehicle Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "vehicle_temperature > 25", "legendFormat": "{{vehicle_id}}" }
   ]
  },
  {
   "title": "Vehicle Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "vehicle_humidity", "legendFormat": "{{vehicle_id}}" }
   ]
  },
  {
   "title": "High Vehicle Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "vehicle_humidity > 75", "legendFormat": "{{vehicle_id}}" }
   ]
  }
 ]
}